version: '1.0.{build}'
image: Visual Studio 2017

branches:
  only:
  - master

environment:
  nodejs_version: "11.9.0"
  matrix:
    - configuration: Debug

init:
  - cmd: git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version

build_script:
  - cmd: dotnet build /p:Configuration=%configuration% /p:TreatWarningsAsErrors=True

test_script:
  - cmd: dotnet test /p:Configuration=%configuration%
